FROM golang:1.22.1-alpine AS builder
RUN apk --no-cache add bash git make gcc g++
RUN apk --no-cache add protobuf # Install Protocol Buffers compiler
RUN git clone https://github.com/edenhill/librdkafka.git \
    && cd librdkafka \
    && ./configure \
    && make \
    && make install
WORKDIR /app
COPY . /app
ENV SERVER_BUILD_DIR=src/build/grpc \
    SERVER_DIR=src/cmd/grpc/main.go \
    TAG=dev \
    PACKAGE=lruCache/poc \
    PROTO_DIR=src/internal/proto/ \
    GRPC_GEN_DIR=.

#WORKDIR src/cmd/grpc
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -tags "musl ${TAG}" -o ${SERVER_BUILD_DIR}/grpc_bin ./${SERVER_DIR}


# Final stage
FROM golang:1.22.1-alpine
RUN apk --no-cache add bash
WORKDIR /
COPY --from=builder /app/src/build/grpc/grpc_bin .
EXPOSE 8080
ENTRYPOINT [ "/grpc_bin" ]