apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXlOakV4TXpnek1sb1hEVE16TURVeU16RXhNemd6TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHZUCnlmUDJ4LzUzaHFhZ3hJU3lUbmdha0dOUFFnT0J1QmJrS3MxNGRwK292bW1WSllBMndEYWduTkI0LzBEbEprYVkKMmxhdGZrUGJweGlnS0lZVTlidWNkYVdYRlQ3RnFtTU41UWNnMlZxUVgvQ2NPejUxbWNKamU4L1BaM1RFTnBFSwpjVnB0Qk9zWk1MWjJzQTd2STZCeUVNVDMxV293TVhZU3NHMUI3bkFsM2YvN09aT0RQM1cxNTQ0S1hYdWNhQzRHCkFMMGN3OW9GVVFFQjBFWk4va084N2tJMTloTzJlMWIrRzBGb2s0OEFXd2JNQlZTdjZBcUtpRHVyWGJYVFdTRnEKZ2FWQ0pxL29WNXU2SzNmNnF2dmpEUFJVZE1PNFFiWGdOK2RaRUZjUnE4MkVnTkpUZjR3dG1SeGxXbzZiUnJ3OQpuZHZ1TWdMWkN5azJZdjJIQnlVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCb0t0Si9aZlg2ZFBBVTRUL3Y4QnBEckNZcFdNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSXo1VHN3UTl4RUZoViszQjNWRwpGOG5jMzlzdU40dk1VZW56bnlQWVk4ekQvM0o1KzQ1TE9sbms2QXJoWStLRVJrd1RKdk1LZTJ1KzRYZ0hZZUdJCmJNY0JIdC8zL1YwTFdBYWlXOTRTc0tueVZIVENpQVZJL1BlZmdJWVh1Vnk2eUpWN1F3amNyZ1NiaXVLMUJrV2YKVTMyRHpTOTlNdlRpVzVmbUJTUEJNV2tRc2k5SVpGcjgrSWNKMFdSK0xSYWcwMk5BdzFsSmI5NE5yN3FYeTVUagp2QUVuWWE5NGJlcnJucGhEREdJa0svK1dEOGxRcU5tYlVHcFJIM0pLYTNSVldZTWdBMlNlNU1obTJ6eUZqVVNNCmNKOHFneE83dTVqRHNqT09SK0pRc05KaGplOFpEVDJjdG9ITWNVL3ByRDJYZktTR0VDMytoOUdwMi9lUFlHSC8KY0lRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://F416576D468AE0489A274678D4138568.gr7.ap-south-1.eks.amazonaws.com
    name: arn:aws:eks:ap-south-1:386937761162:cluster/AWS-MUM-PROD-X-TWO-CORE
contexts:
  - context:
      cluster: arn:aws:eks:ap-south-1:386937761162:cluster/AWS-MUM-PROD-X-TWO-CORE
      user: arn:aws:eks:ap-south-1:386937761162:cluster/AWS-MUM-PROD-X-TWO-CORE
    name: arn:aws:eks:ap-south-1:386937761162:cluster/AWS-MUM-PROD-X-TWO-CORE
current-context: arn:aws:eks:ap-south-1:386937761162:cluster/AWS-MUM-PROD-X-TWO-CORE
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:ap-south-1:386937761162:cluster/AWS-MUM-PROD-X-TWO-CORE
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - ap-south-1
          - eks
          - get-token
          - --cluster-name
          - AWS-MUM-PROD-X-TWO-CORE
        command: aws